generic_data_fetcher:
    cache_location: "gene_descriptions_cache"
    # set 'data_fetcher' to 'agr_data_fetcher' to generate descriptions for AGR or 'wb_data_fetcher' for WormBase
    data_fetcher: "wb_data_fetcher"
    chebi_file_source: "ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi_lite.obo.gz"

# options for WormBase gene description generation - used when data_fetcher is set to 'wb_data_fetcher'
wb_data_fetcher:
    release: "WS265"
    raw_files_source: "ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases"
    organisms_to_process:
        # add the species to be processed to the following list. Entries must have the same text as in 'organisms'
        # option
        - c_elegans
        - b_malayi
        - c_brenneri
        - c_briggsae
        - c_japonica
        - c_remanei
        - o_volvulus
        - p_pacificus
        - s_ratti
    organisms:
        b_malayi:
            project_id: "PRJNA10729"
        c_brenneri:
            project_id: "PRJNA20035"
        c_briggsae:
            project_id: "PRJNA10731"
            main_sister_species: c_elegans
        c_elegans:
            project_id: "PRJNA13758"
        c_japonica:
            project_id: "PRJNA12591"
        c_remanei:
            project_id: "PRJNA53967"
        o_volvulus:
            project_id: "PRJEB513"
        p_pacificus:
            project_id: "PRJNA12644"
        s_ratti:
            project_id: "PRJEB125"
        t_muris:
            project_id: "PRJEB126"

agr_data_fetcher:
    raw_files_source: "https://s3.amazonaws.com/mod-datadumps"
    release: "1.0"
    organisms_to_process:
        - wb
        - fb
        - zfin
        - sgd
        - rgd
        - mgi
    organisms:
        wb:
            name: "c_elegans"
            main_files: "WB_1.0.4_3.tar.gz"
            bgi_file: "WB_1.0.4_BGI.json"
            go_annotations: "gene_association.wb.gz"
        zfin:
            name: "zebra_fish"
            main_files: "ZFIN_1.1_1.tar.gz"
            bgi_file: "ZFIN_1.1_basicGeneInformation.json"
            go_annotations: "gene_association.zfin.gz"
        fb:
            name: "drosophila melanogaster"
            main_files: "FB_1.0.4_4.tar.gz"
            bgi_file: "FB_1.0.4_BGI.json"
            go_annotations: "gene_association.fb.gz"
        rgd:
            name: "rat"
            main_files: "RGD_1.0_4.tar.gz"
            bgi_file: "RGD_1.0_basicGeneInformation.10116.json"
            go_annotations: "gene_association.rgd.gz"
        sgd:
            name: "yeast"
            main_files: "SGD_1.0.3.tar.gz"
            bgi_file: "SGD_1.0.3/SGD_1.0.2_basicGeneInformation.json"
            go_annotations: "gene_association.sgd.gz"
        mgi:
            name: "mouse"
            main_files: "MGI_1.0.6.tar.gz"
            bgi_file: "MGI_1.0.6_basicGeneInformation.json"
            go_annotations: "gene_association.mgi.gz"

generic_genedesc_writer:
    genedesc_writer: "json_writer"

json_writer_options:
    output_dir: "./generated_descriptions"

go_sentences_options:
    exclude_terms:
        - "GO:0008150"
        - "GO:0003674"
        - "GO:0005575"
        - "GO:0005488"
        - "GO:0005515"
        - "GO:0044877"
    rename_terms:
        "molting cycle, collagen and cuticulin-based cuticle": "molting cycle"
        "molting cycle, chitin-based cuticle": "molting cycle"
        "multicellular organism growth": "growth"
        "embryo development ending in birth or egg hatching": "embryo development"
        "synaptic transmission, (\\w+)": "\\1 synaptic transmission"
    evidence_codes:
        EXP:
            group: EXPERIMENTAL
            priority: 1
        IDA:
            group: EXPERIMENTAL
            priority: 2
        IPI:
            group: EXPERIMENTAL
            priority: 3
        IMP:
            group: EXPERIMENTAL
            priority: 4
        IGI:
            group: EXPERIMENTAL
            priority: 5
        IEP:
            group: EXPERIMENTAL
            priority: 6
        HTP:
            group: HIGH_THROUGHPUT_EXPERIMENTAL
            priority: 7
        HDA:
            group: HIGH_THROUGHPUT_EXPERIMENTAL
            priority: 8
        HMP:
            group: HIGH_THROUGHPUT_EXPERIMENTAL
            priority: 9
        HGI:
            group: HIGH_THROUGHPUT_EXPERIMENTAL
            priority: 10
        HEP:
            group: HIGH_THROUGHPUT_EXPERIMENTAL
            priority: 11
        ISS:
            group: PHYLOGENETIC_ANALYSIS_AND_SEQUENCE_BASED_ANALYSIS
            priority: 13
        ISO:
            group: PHYLOGENETIC_ANALYSIS_AND_SEQUENCE_BASED_ANALYSIS
            priority: 14
        ISA:
            group: PHYLOGENETIC_ANALYSIS_AND_SEQUENCE_BASED_ANALYSIS
            priority: 15
        ISM:
            group: PHYLOGENETIC_ANALYSIS_AND_SEQUENCE_BASED_ANALYSIS
            priority: 16
        IBA:
            group: PHYLOGENETIC_ANALYSIS_AND_SEQUENCE_BASED_ANALYSIS
            priority: 12
        IBD:
            group: PHYLOGENETIC_ANALYSIS_AND_SEQUENCE_BASED_ANALYSIS
            priority: 17
        TAS:
            group: INFERRED_BY_CURATORS_AND_AUTHORS
            priority: 18
        IC:
            group: INFERRED_BY_CURATORS_AND_AUTHORS
            priority: 19
        RCA:
            group: ELECTRONIC_AND_COMPUTATIONAL_ANALYSIS
            priority: 21
        IEA:
            group: ELECTRONIC_AND_COMPUTATIONAL_ANALYSIS
            priority: 20
    group_priority:
        EXPERIMENTAL: 1
        HIGH_THROUGHPUT_EXPERIMENTAL: 2
        PHYLOGENETIC_ANALYSIS_AND_SEQUENCE_BASED_ANALYSIS: 3
        INFERRED_BY_CURATORS_AND_AUTHORS: 4
        ELECTRONIC_AND_COMPUTATIONAL_ANALYSIS: 5
    go_prepostfix_sentences_map:
        - aspect: F
          group: EXPERIMENTAL
          qualifier: ""
          prefix: "exhibits"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "structural constituent"
                prefix: "a"
                postfix: ""
        - aspect: F
          group: EXPERIMENTAL
          qualifier: "contributes_to"
          prefix: "contributes to"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "structural constituent"
                prefix: "contributes as a"
                postfix: ""
        - aspect: F
          group: HIGH_THROUGHPUT_EXPERIMENTAL
          qualifier: ""
          prefix: "exhibits"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "structural constituent"
                prefix: "a"
                postfix: ""
        - aspect: F
          group: HIGH_THROUGHPUT_EXPERIMENTAL
          qualifier: "contributes_to"
          prefix: "contributes to"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "structural constituent"
                prefix: "a"
                postfix: ""
        - aspect: F
          group: PHYLOGENETIC_ANALYSIS_AND_SEQUENCE_BASED_ANALYSIS
          qualifier: ""
          prefix: "predicted to have"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "structural constituent"
                prefix: "predicted to be a"
                postfix: ""
        - aspect: F
          group: PHYLOGENETIC_ANALYSIS_AND_SEQUENCE_BASED_ANALYSIS
          qualifier: "contributes_to"
          prefix: "predicted to contribute to"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "structural constituent"
                prefix: "predicted to contribute as a"
                postfix: ""
        - aspect: F
          group: INFERRED_BY_CURATORS_AND_AUTHORS
          qualifier: ""
          prefix: "predicted to have"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "structural constituent"
                prefix: "predicted to be a"
                postfix: ""
        - aspect: F
          group: INFERRED_BY_CURATORS_AND_AUTHORS
          qualifier: "contributes_to"
          prefix: "predicted to contribute to"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "structural constituent"
                prefix: "predicted to contribute as a"
                postfix: ""
        - aspect: F
          group: ELECTRONIC_AND_COMPUTATIONAL_ANALYSIS
          qualifier: ""
          prefix: "predicted to have"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "structural constituent"
                prefix: "predicted to be a"
                postfix: ""
        - aspect: F
          group: ELECTRONIC_AND_COMPUTATIONAL_ANALYSIS
          qualifier: "contributes_to"
          prefix: "predicted to contribute to"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "structural constituent"
                prefix: "predicted to contribute as a"
                postfix: ""
        - aspect: P
          group: EXPERIMENTAL
          qualifier: ""
          prefix: "involved in"
          postfix: ""
          special_cases:
        - aspect: P
          group: HIGH_THROUGHPUT_EXPERIMENTAL
          qualifier: ""
          prefix: "involved in"
          postfix: ""
          special_cases:
        - aspect: P
          group: PHYLOGENETIC_ANALYSIS_AND_SEQUENCE_BASED_ANALYSIS
          qualifier: ""
          prefix: "predicted to be involved in"
          postfix: ""
          special_cases:
        - aspect: P
          group: INFERRED_BY_CURATORS_AND_AUTHORS
          qualifier: ""
          prefix: "predicted to be involved in"
          postfix: ""
          special_cases:
        - aspect: P
          group: ELECTRONIC_AND_COMPUTATIONAL_ANALYSIS
          qualifier: ""
          prefix: "predicted to be involved in"
          postfix: ""
          special_cases:
        - aspect: C
          group: EXPERIMENTAL
          qualifier: ""
          prefix: "localizes to"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "intracellular$"
                prefix: "is"
                postfix: ""
        - aspect: C
          group: EXPERIMENTAL
          qualifier: "colocalizes_with"
          prefix: "colocalizes with"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "intracellular$"
                prefix: "is"
                postfix: ""
        - aspect: C
          group: HIGH_THROUGHPUT_EXPERIMENTAL
          qualifier: ""
          prefix: "localizes to"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "intracellular$"
                prefix: "is"
                postfix: ""
        - aspect: C
          group: HIGH_THROUGHPUT_EXPERIMENTAL
          qualifier: "colocalizes_with"
          prefix: "colocalizes with"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "intracellular$"
                prefix: "is"
                postfix: ""
        - aspect: C
          group: PHYLOGENETIC_ANALYSIS_AND_SEQUENCE_BASED_ANALYSIS
          qualifier: ""
          prefix: "predicted to localize to"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "intracellular$"
                prefix: "predicted to be"
                postfix: ""
        - aspect: C
          group: PHYLOGENETIC_ANALYSIS_AND_SEQUENCE_BASED_ANALYSIS
          qualifier: "colocalizes_with"
          prefix: "predicted to colocalize with"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "intracellular$"
                prefix: "predicted to be"
                postfix: ""
        - aspect: C
          group: INFERRED_BY_CURATORS_AND_AUTHORS
          qualifier: ""
          prefix: "predicted to localize to"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "intracellular$"
                prefix: "predicted to be"
                postfix: ""
        - aspect: C
          group: INFERRED_BY_CURATORS_AND_AUTHORS
          qualifier: "colocalizes_with"
          prefix: "predicted to colocalize with"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "intracellular$"
                prefix: "predicted to be"
                postfix: ""
        - aspect: C
          group: ELECTRONIC_AND_COMPUTATIONAL_ANALYSIS
          qualifier: ""
          prefix: "predicted to localize to"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "intracellular$"
                prefix: "predicted to be"
                postfix: ""
        - aspect: C
          group: ELECTRONIC_AND_COMPUTATIONAL_ANALYSIS
          qualifier: "colocalize_with"
          prefix: "predicted to colocalize with"
          postfix: ""
          special_cases:
              - id: 1
                match_regex: "intracellular$"
                prefix: "predicted to be"
                postfix: ""

    go_truncate_others_aggregation_word: several
    go_truncate_others_terms:
        F: "functions"
        P: "processes"
        C: "cellular components"

    remove_parents_if_children_are_present: true
    trim_terms_by_common_ancestors: true
    trim_if_more_than_terms: 3
    trim_min_distance_from_root: 
        F: 3
        P: 5
        C: 5



